apiVersion: v1
kind: ConfigMap
metadata:
  name: plc-connectors-config
  namespace: {{ .Values.namespace }}
data:
  rockwell.json: |
{{ .Values.config.rockwellJson | indent 4 }}
  siemens-browser.json: |
{{ .Values.config.siemensBrowserJson | indent 4 }}
  siemens-s7.json: |
{{ .Values.config.siemensS7Json | indent 4 }}