apiVersion: v1
kind: Service
metadata:
  name: rockwell-connector
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: rockwell-connector
  ports:
    - name: http
      port: {{ .Values.rockwell.port }}
      targetPort: http