{{- if and .Values.rockwell.ingress.enabled .Values.rockwell.ingress.middlewares.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.rockwell.ingress.middlewares.strip.name }}
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
{{ toYaml .Values.rockwell.ingress.middlewares.strip.prefixes | nindent 6 }}
---
{{- if .Values.rockwell.ingress.middlewares.apiKey.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.rockwell.ingress.middlewares.apiKey.name }}
  namespace: {{ .Values.namespace }}
spec:
  headers:
    customRequestHeaders:
      X-API-Key: {{ .Values.rockwell.ingress.middlewares.apiKey.key | quote }}
{{- end }}
{{- end }}