apiVersion: v1
kind: Service
metadata:
  name: siemens-s7
  namespace: {{ .Values.namespace }}
  labels:
    app: siemens-s7
spec:
  type: ClusterIP
  selector:
    app: siemens-s7
  ports:
    - name: http
      port: {{ .Values.siemensS7.port }}
      targetPort: http