apiVersion: v1
kind: Service
metadata:
  name: siemens-browser
  namespace: {{ .Values.namespace }}
  labels:
    app: siemens-browser
spec:
  type: ClusterIP
  selector:
    app: siemens-browser
  ports:
    - name: http
      port: {{ .Values.siemensBrowser.port }}
      targetPort: http