apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plc-connectors
  namespace: argocd
spec:
  source:
    repoURL: https://contitech.ghe.com/uif60257/ct-plc-connectors.git
    targetRevision: main
    path: helm/plc-connectors
    helm:
      valuesObject:
        namespace: maen-ct-gate

        rockwell:
          enabled: true
          image: artifacts.ws.contitech.cloud/ctmanusdocker-it-ccoqi-smtfc-test-dev/rockwell-connector:0.1.3
          port: 8100

        siemensBrowser:
          enabled: true
          image: artifacts.ws.contitech.cloud/ctmanusdocker-it-ccoqi-smtfc-test-dev/siemens-browser:0.1.3
          port: 8200

        siemensS7:
          enabled: true
          image: artifacts.ws.contitech.cloud/ctmanusdocker-it-ccoqi-smtfc-test-dev/siemens-s7:0.1.3
          port: 8300
          scan:
            dbRanges: ["1-200"]
            blockSize: 256
            maxBytesPerDB: 4096
            throttleMs: 100
  destination:
    name: in-cluster
    namespace: maen-ct-gate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true